/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWinstVerliesRouteImport } from './routes/_authenticated/winst-verlies'
import { Route as AuthenticatedWefactFacturenRouteImport } from './routes/_authenticated/wefact-facturen'
import { Route as AuthenticatedTransactiesRouteImport } from './routes/_authenticated/transacties'
import { Route as AuthenticatedShopifyBetalingenRouteImport } from './routes/_authenticated/shopify-betalingen'
import { Route as AuthenticatedOpenstaandKlantenRouteImport } from './routes/_authenticated/openstaand-klanten'
import { Route as AuthenticatedOmzetaansluitingRouteImport } from './routes/_authenticated/omzetaansluiting'
import { Route as AuthenticatedOmzetKaartRouteImport } from './routes/_authenticated/omzet-kaart'
import { Route as AuthenticatedOmzetGraphRouteImport } from './routes/_authenticated/omzet-graph'
import { Route as AuthenticatedMollieTransactiesRouteImport } from './routes/_authenticated/mollie-transacties'
import { Route as AuthenticatedMollieFacturenRouteImport } from './routes/_authenticated/mollie-facturen'
import { Route as AuthenticatedKassaAansluitingRouteImport } from './routes/_authenticated/kassa-aansluiting'
import { Route as AuthenticatedInstellingenRouteImport } from './routes/_authenticated/instellingen'
import { Route as AuthenticatedImportCsvRouteImport } from './routes/_authenticated/import-csv'
import { Route as AuthenticatedGrootboekRouteImport } from './routes/_authenticated/grootboek'
import { Route as AuthenticatedGebruikersRouteImport } from './routes/_authenticated/gebruikers'
import { Route as AuthenticatedExactTransactiesRouteImport } from './routes/_authenticated/exact-transacties'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBudgettenRouteImport } from './routes/_authenticated/budgetten'
import { Route as AuthenticatedBtwExportRouteImport } from './routes/_authenticated/btw-export'
import { Route as AuthenticatedBoldAfsAansluitingRouteImport } from './routes/_authenticated/bold-afs-aansluiting'
import { Route as AuthenticatedAfsHuurRouteImport } from './routes/_authenticated/afs-huur'
import { Route as AuthenticatedTransactiesIdRouteImport } from './routes/_authenticated/transacties.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWinstVerliesRoute =
  AuthenticatedWinstVerliesRouteImport.update({
    id: '/winst-verlies',
    path: '/winst-verlies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWefactFacturenRoute =
  AuthenticatedWefactFacturenRouteImport.update({
    id: '/wefact-facturen',
    path: '/wefact-facturen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactiesRoute =
  AuthenticatedTransactiesRouteImport.update({
    id: '/transacties',
    path: '/transacties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShopifyBetalingenRoute =
  AuthenticatedShopifyBetalingenRouteImport.update({
    id: '/shopify-betalingen',
    path: '/shopify-betalingen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpenstaandKlantenRoute =
  AuthenticatedOpenstaandKlantenRouteImport.update({
    id: '/openstaand-klanten',
    path: '/openstaand-klanten',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmzetaansluitingRoute =
  AuthenticatedOmzetaansluitingRouteImport.update({
    id: '/omzetaansluiting',
    path: '/omzetaansluiting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmzetKaartRoute = AuthenticatedOmzetKaartRouteImport.update({
  id: '/omzet-kaart',
  path: '/omzet-kaart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmzetGraphRoute = AuthenticatedOmzetGraphRouteImport.update({
  id: '/omzet-graph',
  path: '/omzet-graph',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMollieTransactiesRoute =
  AuthenticatedMollieTransactiesRouteImport.update({
    id: '/mollie-transacties',
    path: '/mollie-transacties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMollieFacturenRoute =
  AuthenticatedMollieFacturenRouteImport.update({
    id: '/mollie-facturen',
    path: '/mollie-facturen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKassaAansluitingRoute =
  AuthenticatedKassaAansluitingRouteImport.update({
    id: '/kassa-aansluiting',
    path: '/kassa-aansluiting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstellingenRoute =
  AuthenticatedInstellingenRouteImport.update({
    id: '/instellingen',
    path: '/instellingen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportCsvRoute = AuthenticatedImportCsvRouteImport.update({
  id: '/import-csv',
  path: '/import-csv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrootboekRoute = AuthenticatedGrootboekRouteImport.update({
  id: '/grootboek',
  path: '/grootboek',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGebruikersRoute = AuthenticatedGebruikersRouteImport.update({
  id: '/gebruikers',
  path: '/gebruikers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExactTransactiesRoute =
  AuthenticatedExactTransactiesRouteImport.update({
    id: '/exact-transacties',
    path: '/exact-transacties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgettenRoute = AuthenticatedBudgettenRouteImport.update({
  id: '/budgetten',
  path: '/budgetten',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBtwExportRoute = AuthenticatedBtwExportRouteImport.update({
  id: '/btw-export',
  path: '/btw-export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoldAfsAansluitingRoute =
  AuthenticatedBoldAfsAansluitingRouteImport.update({
    id: '/bold-afs-aansluiting',
    path: '/bold-afs-aansluiting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAfsHuurRoute = AuthenticatedAfsHuurRouteImport.update({
  id: '/afs-huur',
  path: '/afs-huur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactiesIdRoute =
  AuthenticatedTransactiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTransactiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/afs-huur': typeof AuthenticatedAfsHuurRoute
  '/bold-afs-aansluiting': typeof AuthenticatedBoldAfsAansluitingRoute
  '/btw-export': typeof AuthenticatedBtwExportRoute
  '/budgetten': typeof AuthenticatedBudgettenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exact-transacties': typeof AuthenticatedExactTransactiesRoute
  '/gebruikers': typeof AuthenticatedGebruikersRoute
  '/grootboek': typeof AuthenticatedGrootboekRoute
  '/import-csv': typeof AuthenticatedImportCsvRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/kassa-aansluiting': typeof AuthenticatedKassaAansluitingRoute
  '/mollie-facturen': typeof AuthenticatedMollieFacturenRoute
  '/mollie-transacties': typeof AuthenticatedMollieTransactiesRoute
  '/omzet-graph': typeof AuthenticatedOmzetGraphRoute
  '/omzet-kaart': typeof AuthenticatedOmzetKaartRoute
  '/omzetaansluiting': typeof AuthenticatedOmzetaansluitingRoute
  '/openstaand-klanten': typeof AuthenticatedOpenstaandKlantenRoute
  '/shopify-betalingen': typeof AuthenticatedShopifyBetalingenRoute
  '/transacties': typeof AuthenticatedTransactiesRouteWithChildren
  '/wefact-facturen': typeof AuthenticatedWefactFacturenRoute
  '/winst-verlies': typeof AuthenticatedWinstVerliesRoute
  '/transacties/$id': typeof AuthenticatedTransactiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/afs-huur': typeof AuthenticatedAfsHuurRoute
  '/bold-afs-aansluiting': typeof AuthenticatedBoldAfsAansluitingRoute
  '/btw-export': typeof AuthenticatedBtwExportRoute
  '/budgetten': typeof AuthenticatedBudgettenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exact-transacties': typeof AuthenticatedExactTransactiesRoute
  '/gebruikers': typeof AuthenticatedGebruikersRoute
  '/grootboek': typeof AuthenticatedGrootboekRoute
  '/import-csv': typeof AuthenticatedImportCsvRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/kassa-aansluiting': typeof AuthenticatedKassaAansluitingRoute
  '/mollie-facturen': typeof AuthenticatedMollieFacturenRoute
  '/mollie-transacties': typeof AuthenticatedMollieTransactiesRoute
  '/omzet-graph': typeof AuthenticatedOmzetGraphRoute
  '/omzet-kaart': typeof AuthenticatedOmzetKaartRoute
  '/omzetaansluiting': typeof AuthenticatedOmzetaansluitingRoute
  '/openstaand-klanten': typeof AuthenticatedOpenstaandKlantenRoute
  '/shopify-betalingen': typeof AuthenticatedShopifyBetalingenRoute
  '/transacties': typeof AuthenticatedTransactiesRouteWithChildren
  '/wefact-facturen': typeof AuthenticatedWefactFacturenRoute
  '/winst-verlies': typeof AuthenticatedWinstVerliesRoute
  '/transacties/$id': typeof AuthenticatedTransactiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/afs-huur': typeof AuthenticatedAfsHuurRoute
  '/_authenticated/bold-afs-aansluiting': typeof AuthenticatedBoldAfsAansluitingRoute
  '/_authenticated/btw-export': typeof AuthenticatedBtwExportRoute
  '/_authenticated/budgetten': typeof AuthenticatedBudgettenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exact-transacties': typeof AuthenticatedExactTransactiesRoute
  '/_authenticated/gebruikers': typeof AuthenticatedGebruikersRoute
  '/_authenticated/grootboek': typeof AuthenticatedGrootboekRoute
  '/_authenticated/import-csv': typeof AuthenticatedImportCsvRoute
  '/_authenticated/instellingen': typeof AuthenticatedInstellingenRoute
  '/_authenticated/kassa-aansluiting': typeof AuthenticatedKassaAansluitingRoute
  '/_authenticated/mollie-facturen': typeof AuthenticatedMollieFacturenRoute
  '/_authenticated/mollie-transacties': typeof AuthenticatedMollieTransactiesRoute
  '/_authenticated/omzet-graph': typeof AuthenticatedOmzetGraphRoute
  '/_authenticated/omzet-kaart': typeof AuthenticatedOmzetKaartRoute
  '/_authenticated/omzetaansluiting': typeof AuthenticatedOmzetaansluitingRoute
  '/_authenticated/openstaand-klanten': typeof AuthenticatedOpenstaandKlantenRoute
  '/_authenticated/shopify-betalingen': typeof AuthenticatedShopifyBetalingenRoute
  '/_authenticated/transacties': typeof AuthenticatedTransactiesRouteWithChildren
  '/_authenticated/wefact-facturen': typeof AuthenticatedWefactFacturenRoute
  '/_authenticated/winst-verlies': typeof AuthenticatedWinstVerliesRoute
  '/_authenticated/transacties/$id': typeof AuthenticatedTransactiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/afs-huur'
    | '/bold-afs-aansluiting'
    | '/btw-export'
    | '/budgetten'
    | '/dashboard'
    | '/exact-transacties'
    | '/gebruikers'
    | '/grootboek'
    | '/import-csv'
    | '/instellingen'
    | '/kassa-aansluiting'
    | '/mollie-facturen'
    | '/mollie-transacties'
    | '/omzet-graph'
    | '/omzet-kaart'
    | '/omzetaansluiting'
    | '/openstaand-klanten'
    | '/shopify-betalingen'
    | '/transacties'
    | '/wefact-facturen'
    | '/winst-verlies'
    | '/transacties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/afs-huur'
    | '/bold-afs-aansluiting'
    | '/btw-export'
    | '/budgetten'
    | '/dashboard'
    | '/exact-transacties'
    | '/gebruikers'
    | '/grootboek'
    | '/import-csv'
    | '/instellingen'
    | '/kassa-aansluiting'
    | '/mollie-facturen'
    | '/mollie-transacties'
    | '/omzet-graph'
    | '/omzet-kaart'
    | '/omzetaansluiting'
    | '/openstaand-klanten'
    | '/shopify-betalingen'
    | '/transacties'
    | '/wefact-facturen'
    | '/winst-verlies'
    | '/transacties/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/afs-huur'
    | '/_authenticated/bold-afs-aansluiting'
    | '/_authenticated/btw-export'
    | '/_authenticated/budgetten'
    | '/_authenticated/dashboard'
    | '/_authenticated/exact-transacties'
    | '/_authenticated/gebruikers'
    | '/_authenticated/grootboek'
    | '/_authenticated/import-csv'
    | '/_authenticated/instellingen'
    | '/_authenticated/kassa-aansluiting'
    | '/_authenticated/mollie-facturen'
    | '/_authenticated/mollie-transacties'
    | '/_authenticated/omzet-graph'
    | '/_authenticated/omzet-kaart'
    | '/_authenticated/omzetaansluiting'
    | '/_authenticated/openstaand-klanten'
    | '/_authenticated/shopify-betalingen'
    | '/_authenticated/transacties'
    | '/_authenticated/wefact-facturen'
    | '/_authenticated/winst-verlies'
    | '/_authenticated/transacties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/winst-verlies': {
      id: '/_authenticated/winst-verlies'
      path: '/winst-verlies'
      fullPath: '/winst-verlies'
      preLoaderRoute: typeof AuthenticatedWinstVerliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wefact-facturen': {
      id: '/_authenticated/wefact-facturen'
      path: '/wefact-facturen'
      fullPath: '/wefact-facturen'
      preLoaderRoute: typeof AuthenticatedWefactFacturenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transacties': {
      id: '/_authenticated/transacties'
      path: '/transacties'
      fullPath: '/transacties'
      preLoaderRoute: typeof AuthenticatedTransactiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shopify-betalingen': {
      id: '/_authenticated/shopify-betalingen'
      path: '/shopify-betalingen'
      fullPath: '/shopify-betalingen'
      preLoaderRoute: typeof AuthenticatedShopifyBetalingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/openstaand-klanten': {
      id: '/_authenticated/openstaand-klanten'
      path: '/openstaand-klanten'
      fullPath: '/openstaand-klanten'
      preLoaderRoute: typeof AuthenticatedOpenstaandKlantenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/omzetaansluiting': {
      id: '/_authenticated/omzetaansluiting'
      path: '/omzetaansluiting'
      fullPath: '/omzetaansluiting'
      preLoaderRoute: typeof AuthenticatedOmzetaansluitingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/omzet-kaart': {
      id: '/_authenticated/omzet-kaart'
      path: '/omzet-kaart'
      fullPath: '/omzet-kaart'
      preLoaderRoute: typeof AuthenticatedOmzetKaartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/omzet-graph': {
      id: '/_authenticated/omzet-graph'
      path: '/omzet-graph'
      fullPath: '/omzet-graph'
      preLoaderRoute: typeof AuthenticatedOmzetGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mollie-transacties': {
      id: '/_authenticated/mollie-transacties'
      path: '/mollie-transacties'
      fullPath: '/mollie-transacties'
      preLoaderRoute: typeof AuthenticatedMollieTransactiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mollie-facturen': {
      id: '/_authenticated/mollie-facturen'
      path: '/mollie-facturen'
      fullPath: '/mollie-facturen'
      preLoaderRoute: typeof AuthenticatedMollieFacturenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kassa-aansluiting': {
      id: '/_authenticated/kassa-aansluiting'
      path: '/kassa-aansluiting'
      fullPath: '/kassa-aansluiting'
      preLoaderRoute: typeof AuthenticatedKassaAansluitingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instellingen': {
      id: '/_authenticated/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof AuthenticatedInstellingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-csv': {
      id: '/_authenticated/import-csv'
      path: '/import-csv'
      fullPath: '/import-csv'
      preLoaderRoute: typeof AuthenticatedImportCsvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grootboek': {
      id: '/_authenticated/grootboek'
      path: '/grootboek'
      fullPath: '/grootboek'
      preLoaderRoute: typeof AuthenticatedGrootboekRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gebruikers': {
      id: '/_authenticated/gebruikers'
      path: '/gebruikers'
      fullPath: '/gebruikers'
      preLoaderRoute: typeof AuthenticatedGebruikersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exact-transacties': {
      id: '/_authenticated/exact-transacties'
      path: '/exact-transacties'
      fullPath: '/exact-transacties'
      preLoaderRoute: typeof AuthenticatedExactTransactiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgetten': {
      id: '/_authenticated/budgetten'
      path: '/budgetten'
      fullPath: '/budgetten'
      preLoaderRoute: typeof AuthenticatedBudgettenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/btw-export': {
      id: '/_authenticated/btw-export'
      path: '/btw-export'
      fullPath: '/btw-export'
      preLoaderRoute: typeof AuthenticatedBtwExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bold-afs-aansluiting': {
      id: '/_authenticated/bold-afs-aansluiting'
      path: '/bold-afs-aansluiting'
      fullPath: '/bold-afs-aansluiting'
      preLoaderRoute: typeof AuthenticatedBoldAfsAansluitingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/afs-huur': {
      id: '/_authenticated/afs-huur'
      path: '/afs-huur'
      fullPath: '/afs-huur'
      preLoaderRoute: typeof AuthenticatedAfsHuurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transacties/$id': {
      id: '/_authenticated/transacties/$id'
      path: '/$id'
      fullPath: '/transacties/$id'
      preLoaderRoute: typeof AuthenticatedTransactiesIdRouteImport
      parentRoute: typeof AuthenticatedTransactiesRoute
    }
  }
}

interface AuthenticatedTransactiesRouteChildren {
  AuthenticatedTransactiesIdRoute: typeof AuthenticatedTransactiesIdRoute
}

const AuthenticatedTransactiesRouteChildren: AuthenticatedTransactiesRouteChildren =
  {
    AuthenticatedTransactiesIdRoute: AuthenticatedTransactiesIdRoute,
  }

const AuthenticatedTransactiesRouteWithChildren =
  AuthenticatedTransactiesRoute._addFileChildren(
    AuthenticatedTransactiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAfsHuurRoute: typeof AuthenticatedAfsHuurRoute
  AuthenticatedBoldAfsAansluitingRoute: typeof AuthenticatedBoldAfsAansluitingRoute
  AuthenticatedBtwExportRoute: typeof AuthenticatedBtwExportRoute
  AuthenticatedBudgettenRoute: typeof AuthenticatedBudgettenRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExactTransactiesRoute: typeof AuthenticatedExactTransactiesRoute
  AuthenticatedGebruikersRoute: typeof AuthenticatedGebruikersRoute
  AuthenticatedGrootboekRoute: typeof AuthenticatedGrootboekRoute
  AuthenticatedImportCsvRoute: typeof AuthenticatedImportCsvRoute
  AuthenticatedInstellingenRoute: typeof AuthenticatedInstellingenRoute
  AuthenticatedKassaAansluitingRoute: typeof AuthenticatedKassaAansluitingRoute
  AuthenticatedMollieFacturenRoute: typeof AuthenticatedMollieFacturenRoute
  AuthenticatedMollieTransactiesRoute: typeof AuthenticatedMollieTransactiesRoute
  AuthenticatedOmzetGraphRoute: typeof AuthenticatedOmzetGraphRoute
  AuthenticatedOmzetKaartRoute: typeof AuthenticatedOmzetKaartRoute
  AuthenticatedOmzetaansluitingRoute: typeof AuthenticatedOmzetaansluitingRoute
  AuthenticatedOpenstaandKlantenRoute: typeof AuthenticatedOpenstaandKlantenRoute
  AuthenticatedShopifyBetalingenRoute: typeof AuthenticatedShopifyBetalingenRoute
  AuthenticatedTransactiesRoute: typeof AuthenticatedTransactiesRouteWithChildren
  AuthenticatedWefactFacturenRoute: typeof AuthenticatedWefactFacturenRoute
  AuthenticatedWinstVerliesRoute: typeof AuthenticatedWinstVerliesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAfsHuurRoute: AuthenticatedAfsHuurRoute,
  AuthenticatedBoldAfsAansluitingRoute: AuthenticatedBoldAfsAansluitingRoute,
  AuthenticatedBtwExportRoute: AuthenticatedBtwExportRoute,
  AuthenticatedBudgettenRoute: AuthenticatedBudgettenRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExactTransactiesRoute: AuthenticatedExactTransactiesRoute,
  AuthenticatedGebruikersRoute: AuthenticatedGebruikersRoute,
  AuthenticatedGrootboekRoute: AuthenticatedGrootboekRoute,
  AuthenticatedImportCsvRoute: AuthenticatedImportCsvRoute,
  AuthenticatedInstellingenRoute: AuthenticatedInstellingenRoute,
  AuthenticatedKassaAansluitingRoute: AuthenticatedKassaAansluitingRoute,
  AuthenticatedMollieFacturenRoute: AuthenticatedMollieFacturenRoute,
  AuthenticatedMollieTransactiesRoute: AuthenticatedMollieTransactiesRoute,
  AuthenticatedOmzetGraphRoute: AuthenticatedOmzetGraphRoute,
  AuthenticatedOmzetKaartRoute: AuthenticatedOmzetKaartRoute,
  AuthenticatedOmzetaansluitingRoute: AuthenticatedOmzetaansluitingRoute,
  AuthenticatedOpenstaandKlantenRoute: AuthenticatedOpenstaandKlantenRoute,
  AuthenticatedShopifyBetalingenRoute: AuthenticatedShopifyBetalingenRoute,
  AuthenticatedTransactiesRoute: AuthenticatedTransactiesRouteWithChildren,
  AuthenticatedWefactFacturenRoute: AuthenticatedWefactFacturenRoute,
  AuthenticatedWinstVerliesRoute: AuthenticatedWinstVerliesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
