// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const browserOrigin = typeof window !== 'undefined' ? window.location.origin : undefined;
  const SUPABASE_URL = firstRealUrl(
    import.meta.env.VITE_SUPABASE_URL,
    typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined,
    browserOrigin,
  );
  const SUPABASE_PUBLISHABLE_KEY =
    realEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) ||
    realEnvValue(typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined) ||
    'local-anon-key';

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

function firstRealUrl(...values: Array<string | undefined>) {
  return values.map(realEnvValue).find((value) => value && !isPlaceholderUrl(value));
}

function realEnvValue(value: string | undefined) {
  const trimmed = String(value ?? '').trim();
  if (!trimmed || trimmed === 'undefined' || trimmed === 'null') return undefined;
  return trimmed;
}

function isPlaceholderUrl(value: string) {
  return value.includes('your-api-host.example.com') || value.includes('example.com');
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
